### ISSUE TITLE
Pagination issues in SICP maths book

### ISSUE THREAD

**Issue by danielweck** [readium/r2-testapp-kotlin#112]
Issue originally reported here:
https://github.com/sarabander/sicp/issues/29#issuecomment-426548507

@naorunaoru said:
> R2 Reader on Android 9 (Pixel 2 XL) has weird pagination issues, when page is stuck inbetween transition. Scroll mode works fine though. Otherwise it renders text just as R2 on iOS. :)

Test EPUB
https://github.com/sarabander/sicp-epub/blob/master/sicp.epub
(see https://github.com/sarabander/sicp )

Related issue: https://github.com/readium/r2-testapp-swift/issues/212

**Comment by naorunaoru** [comment]
[Screenshots for reference](https://photos.app.goo.gl/7MusjZCy4VkzUaba7). 

This happens when I swipe to the next page.

**Comment by danielweck** [comment]
Awesome, thank you so much for taking the time to report bugs and upload screenshots! :)

**Comment by pavelric** [comment]
Hello, this is now fixed with https://github.com/readium/r2-navigator-kotlin/pull/38
