### ISSUE TITLE
Missing one thing?

### ISSUE THREAD

**Issue by ycsghr** [readium/r2-testapp-kotlin#113]
![image](https://user-images.githubusercontent.com/34826145/46648861-736a2000-cbc9-11e8-8346-42ba1ac21961.png)

**Comment by aferditamuriqi** [comment]
Hi @ycsghr, can you please make sure you're using the current branches and maybe follow the instructions here https://github.com/readium/r2-workspace-kotlin (if you haven't seen this already) 
I am closing this issue, but if you're facing the same issue or new ones, either file a new issue or join us in https://readium.slack.com/
