### ISSUE TITLE
Swiping is not consistent

### ISSUE THREAD

**Issue by pavelric** [readium/r2-testapp-kotlin#121]
Tried swiping on the different samples : sometimes entire resources/chapters will be skipped although I just tried to swipe to the previous/next page.

**Comment by aferditamuriqi** [comment]
This is a known issue though on both iOS and Android. and I've been working on solving it.

**Comment by HadrienGardeur** [comment]
@aferditamuriqi it's really not comparable. 

On Android, this happens pretty much all the time whereas on iOS I've only seen it when going very very fast using taps.

**Comment by aferditamuriqi** [comment]
@HadrienGardeur I am not comparing it, I am very much aware of the exact issue on Android and working on it. As you know the new swipe has just been implemented and going from one resource to another especially when going back a resource is where the majority of this issue applies. the work we have done over the last few weeks on locators and also the WebPager just needs some finalization on this issue. as I have mentioned before.
