### ISSUE TITLE
LCP issues

### ISSUE THREAD

**Issue by ThanhNguyen1011** [readium/r2-testapp-kotlin#138]
In Gumi company, we're testing the function LCP.
We can't download the encrypted EPUB on some Android devices, we have some problem as below:
    - On Simulator 8.0: can't download the EPUB
    [Video link](https://drive.google.com/file/d/1KrB1dDfVDN2WiUoeUtEgxq1oQX-zVWIB/view?usp=sharing)
    - Samsung Galaxy S7 firmware 7.0: the app stuck at input passphrase screen.
[Video link](https://drive.google.com/file/d/1YPQYV6EYAC1V68FEb-B_paFm75pV144n/view?usp=sharing)
    - Samsung Galaxy S8 firmware 8.0: no problem, can download and read normally.
[Video link](https://drive.google.com/file/d/1xMnCejUFtgIBi7i_U5TaGuUddeFFgzZC/view?usp=sharing)
    
With these issues, we don't see any logs about the problem. So, we can't investigate for fixing it, only see it stuck when call the function below.

    `private fun lcpThread(bytes: ByteArray, progress: ProgressDialog) {
        val lcpLicense = LcpLicense(bytes, this)
        task {
        lcpLicense.fetchStatusDocument().get()
        }
        ...
    }`

We also check the new source on Github or download directly the app from Google Play store for checking but the problem still there.
Can you check and give your advice about this issue?
Thank you for your support!
@llemeurfr

**Comment by aferditamuriqi** [comment]
@ThanhNguyen1011 it is correct that it won't work on the emulator, and I am looking into the SDK 7 issue that you reported on a device, I do not have the exact same device, but I'll see what I can test with

**Comment by ThanhNguyen1011** [comment]
@aferditamuriqi .I have downloaded the git branch above and tested on the devices that is failed for LCP. It worked well. Thank you for your support!.

**Comment by aferditamuriqi** [comment]
Changes have been merged to develop
