### ISSUE TITLE
Bump to Kotlin 1.3

### ISSUE THREAD

**Issue by ErikHellman** [readium/r2-testapp-kotlin#141]
Since Kotlin 1.3 is now released we would like to bump the version of all Readium Kotlin repos to the latest version. The main reason to switch to 1.3 would be to be able to use the stable (1.0) release of Kotlin Coroutines. Coroutines would allow us to easier write Android lifecycle aware asynchronous code, see https://github.com/Kotlin/kotlinx.coroutines for details. Also see https://codelabs.developers.google.com/codelabs/kotlin-coroutines/ for an example of using this in an Android app.

**Comment by HadrienGardeur** [comment]
This seems particularly relevant for the streamer where a number of things should be handled asynchronously:

- parsing media overlays
- calculating positions
- decrypting content
