### ISSUE TITLE
TTS

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-testapp-kotlin#147]
Develop a TTS module and integrate it in the test app. 

An icon at the top of the reading view takes the form of headphones. This is how TTS is activated/de-activated. 
Utterances (sentences) are selected sequencially and highlighted whilst a synthetic voice is reading the text. 
The reading position follows the current utterance. 
The system moves automatically from chapter to chapter.
The user has control over the progression: he can select a new starting point; he can swipe / move to another page or chapter / use the ToC. This corresponds to the concept of "escapability" for sighted people (visually impaired people will use the a11y features provided by screen readers). 

Footnotes: to be discussed if they are read or not, optionally or not.

**Comment by llemeurfr** [comment]
see https://github.com/readium/architecture/blob/master/tts/README.md

**Comment by HadrienGardeur** [comment]
I wouldn't consider this closed since we want to update this feature pretty heavily this year:

- use the decorator API to highlight content on the page as it is read, instead of using a separate view
- turn pages or scroll the view while the text is read aloud

**Comment by llemeurfr** [comment]
This is true but this epic was stale since its creation and not associated with issues. Don't hesitate to re-open it when the dev starts on this update.
