### ISSUE TITLE
Use WebViewCompat instead of platform API

### ISSUE THREAD

**Issue by ErikHellman** [readium/r2-testapp-kotlin#149]
Currently, the implementation used for Readium uses the platform `WebView` and related classes. The recommendation today is to use the compat version [`WebViewCompat`](https://developer.android.com/reference/androidx/webkit/WebViewCompat) as that will more gracefully deal with older APIs versions and differences in Android versions.

See https://www.youtube.com/watch?v=HGZYtDZhOEQ for more information.

**Comment by aferditamuriqi** [comment]
@mmenu-mantano can we close this?
