### ISSUE TITLE
fast swipe could end up swiping a resource instead a page within a resource 

### ISSUE THREAD

**Issue by aferditamuriqi** [readium/r2-testapp-kotlin#153]
this happens because the resource hasn't been fully rendered and laid out yet,  and therefore could be treated as end of a resource or start of a resource

**Comment by aferditamuriqi** [comment]
With fixing the #152 this seems to now not be an issue anymore as well, @llemeurfr  I'll test a bit more and we can then probably close this

**Comment by llemeurfr** [comment]
I just tested the V2.0.0-beta.3 on our tablet (Huawei BTV-W09, Android 6.0) and I can't reproduce the bug anymore.
I let others give their feedback.

**Comment by HadrienGardeur** [comment]
I can still swipe to the next resource with an edge swipe.

**Comment by llemeurfr** [comment]
@HadrienGardeur can you give more details (Android version, hardware)? I tried ten minutes back and forth before commenting the issue.

**Comment by HadrienGardeur** [comment]
Pixel 2XL running the latest security patch for Android 9.0.
