### ISSUE TITLE
hide resource until it has been fully rendered and  laid out

### ISSUE THREAD

**Issue by aferditamuriqi** [readium/r2-testapp-kotlin#154]
this will help avoid the quick flickering that can happen while swiping to the previous resource.

**Comment by aferditamuriqi** [comment]
With fixing the #152 this seems to now not be an issue anymore as well, @llemeurfr  I'll test a bit more and we can then probably close this

**Comment by HadrienGardeur** [comment]
I don't think this is necessarily tied to #152.

If you have a short resource and then a long resource, you can still easily encounter that issue. Try reading any book from Proust for example.

**Comment by aferditamuriqi** [comment]
Hadrien, I haven’t sent out the testapp version with this fix yet. Therefore I would like to get that tested once it is sent out, I haven’t encountered any issue like this with the new version
