### ISSUE TITLE
LCP: DRM Management Activity UI is cut off for Loans

### ISSUE THREAD

**Issue by aferditamuriqi** [readium/r2-testapp-kotlin#175]
![Screenshot_1548892134.png](https://images.zenhubusercontent.com/579d606ae40e5714b16cbc9f/c8d09d6f-20cd-4d3b-ae31-5edae7068e07)

**Comment by llemeurfr** [comment]
Just a note about the date format: it is a US formatted date, difficult to understand for other people (more info about this weird habit in https://www.youtube.com/watch?v=uQj6x5DClZI). 

Could we enjoy an e.g. "05 Feb. 2019" formatted date?

**Comment by llemeurfr** [comment]
I don't understand what cut off means here. 

Also, tiny note about the license type at the top, I'd prefer "LCP" (capital).

**Comment by aferditamuriqi** [comment]
@llemeurfr that's true the date format needs to be updated as well. 
as of the cutoff, I meant you can't scroll to see the actions to renew or return the license.
