### ISSUE TITLE
Crash: App crashes when parsing an EPUB with Media Overlay

### ISSUE THREAD

**Issue by rkwright** [readium/r2-testapp-kotlin#181]
#### Expected Behaviour
App shouldn't crash even if it cannot parse the content

#### Observed behaviour
Instead, the app apparently crashes while loading/parsing the EPUB 

#### Steps to reproduce
1. Try to load the EPUB Test Suite Media Overlays test, 120: [here](http://epubtest.org/epubs/epub30-test-0120-20160116.epub) 
2. Then observe that the app simply quits.  No error message.

#### Test file(s)
See above

### Product
R2 Android-Kotlin app, version 2.0.0-Beta 4

### Platform
Android 6.0
ASUS Zen Pad

#### Additional information
None

**Comment by aferditamuriqi** [comment]
Seem like the issue here is not really the media overlay, but I am evaluating further. 
what i got so far is that in the example attached above the date seem to be wrong 
```    org.joda.time.IllegalFieldValueException: Cannot parse "2013-14-01T13:00:00Z": Value 14 for monthOfYear must be in the range [1,12]```

**Comment by aferditamuriqi** [comment]
yes i can confirm that was the actual issue, and will push a fix for it, the media overlay itself isn't the issue here
