### ISSUE TITLE
Crash: App crashes when first time install on Samsung S8(Android Pie)

### ISSUE THREAD

**Issue by leyvien** [readium/r2-testapp-kotlin#187]
App crashes when first time install on Samsung S8(Android Pie), then open app again, open epub the webview show error "ERR_CLEARTEXT_NOT_PERMITTED"
-missing this line in manifest file:
`<application
    ....
    android:usesCleartextTraffic="true"
    ....>`

**Comment by aferditamuriqi** [comment]
@leyvien this has been fixed in our latest beta, look out for it in the next few days.
