### ISSUE TITLE
Load image even if it is not declared in content.opf

### ISSUE THREAD

**Issue by cges30901** [readium/r2-testapp-kotlin#194]
Version: 2.0.0-beta.4
Hello, I am a new user of Readium. When I open some epub files with Readium, images are not shown, but other epub viewers can show the image correctly. I guess it is because the image is not declared in content.opf. Can you fix this?
![Screenshot_20190404-231910](https://user-images.githubusercontent.com/19516286/55567467-4b9ae580-5730-11e9-8fb2-eebad2f6aff9.png)
[image.epub.zip](https://github.com/readium/r2-testapp-kotlin/files/3044183/image.epub.zip)

**Comment by HadrienGardeur** [comment]
I don't think it's reasonable to handle content that isn't declared in the OPF. This EPUB should be rejected by epubcheck.

**Comment by cges30901** [comment]
OK, but it is inconvenient to fix the epub, though.

**Comment by llemeurfr** [comment]
It's commonly considered that EPUB reading software are not required to handle badly constructed EPUB files. Broken EPUBs are harmful, as different EPUB reading systems handle errors differently, adding to the interoperability issues we already suffer from.
