### ISSUE TITLE
Screen brightness changes when I open user settings

### ISSUE THREAD

**Issue by cges30901** [readium/r2-testapp-kotlin#195]
Version: 2.0.0-beta.4
Hello, when I am reading epub and open user settings, the screen brightness changes and becomes very bright. I think screen brightness shouldn't change when user settings is opened.

Short video demonstrating this issue: https://youtu.be/sMsnRBrhpic

**Comment by HadrienGardeur** [comment]
I would keep that one open as brightness is already within scope of our test app and we need to make sure that we don't have an incorrect implementation (implementers will look at our code when working on their own).

**Comment by cges30901** [comment]
This bug no longer happens if I comment out [this line](https://github.com/readium/r2-testapp-kotlin/blob/6f0f5d8ab7758371babf47458d1b9963ec5bce49/r2-testapp/src/main/java/org/readium/r2/testapp/UserSettings.kt#L546). Since I am not good at Android programming, I don't know what this does. But everything looks fine to me if it is commented out.
