### ISSUE TITLE
FR: lock screen orientation

### ISSUE THREAD

**Issue by cges30901** [readium/r2-testapp-kotlin#197]
Version: 2.0.0-beta.4
I think it is annoying if the screen rotates automatically when I read. So it would be convenient if I can lock screen orientation in landscape or portrait mode.

**Comment by HadrienGardeur** [comment]
IMO this is a feature that can easily be implemented by apps and that doesn't need to be handled in a test app.

I would propose closing this issue.

**Comment by cges30901** [comment]
I didn't know that this app is just for testing and also not aimed at end-users (at least not apparent from Google Play). Closing my issues.

**Comment by llemeurfr** [comment]
I agree that the test app is there to provide a proper test of the underlying open-source modules.
