### ISSUE TITLE
ERR_CONNECTION_REFUSED when scrolling more than one page on Pixel C

### ISSUE THREAD

**Issue by stevenzeck** [readium/r2-testapp-kotlin#199]
I've tried this from both the Google Play Store version and running it locally in Android Studio connected to my Pixel C. When I open a book, any time I scroll more than one page in either direction, I get the webpage not available...connection refused error.

It seems fine on my Pixel phone, so I don't know if there is an OS issue (8.1 vs 9.0), device limitations, or just not the correct settings.

**Comment by stevenzeck** [comment]
Here is a screenshot. I haven't looked at the code thoroughly, but looks like it could be a streamer and/or navigator issue.

Nothing is being logged to the console.

![Screenshot_20190528-152356](https://user-images.githubusercontent.com/8315038/58579787-5befae00-8211-11e9-8409-04815e8f5fd7.png)

**Comment by stevenzeck** [comment]
@aferditamuriqi any thoughts on this?

**Comment by aferditamuriqi** [comment]
@stevenzeck I haven't been able to reproduce this yet, I'll look into it next week again and get back to you with feedback or questions.

**Comment by stevenzeck** [comment]
I did a factory reset, that seemed to clear it up. No clue what could have happened to the device to cause that. I'll reopen if it happens again.
