### ISSUE TITLE
warning on r2-lcp

### ISSUE THREAD

**Issue by leyvien** [readium/r2-testapp-kotlin#206]
WARNING: API 'variant.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getPackageLibrary(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: r2-lcp

**Comment by aferditamuriqi** [comment]
this is an android plugin warning and should not have any impact on building or using the R2 modules, i would think that once whatever plugin that is will be updated this wearing will disappear, I've already double check and there is nothing that I can find on our end to do. I am closing this issue.
