### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by nurzhaussyn** [readium/r2-testapp-kotlin#211]
<img width="1280" alt="Снимок экрана 2019-06-14 в 14 40 18" src="https://user-images.githubusercontent.com/16848122/59496444-40440300-8eb3-11e9-8786-8d6378eee10e.png">

OS: Mac 
AS: 3.2

I added these libraries because of error when first build

    implementation 'com.github.readium:r2-shared-kotlin:1.0.3'
    implementation 'com.github.readium:r2-streamer-kotlin:1.0.3'
    implementation 'com.github.readium:r2-navigator-kotlin:1.0.3'
    implementation 'com.github.readium:r2-opds-kotlin:1.0.3'

But after i get errors in img. How solve it ? Help

**Comment by nurzhaussyn** [comment]
<img width="1280" alt="Снимок экрана 2019-06-14 в 15 04 53" src="https://user-images.githubusercontent.com/16848122/59497725-ccefc080-8eb5-11e9-83a6-a110b4840225.png">

I have other errors when used last versions of mentioned libraries. But i tried to comment this fields from code but i get error with lcp. Otherwise i dont use lcp

**Comment by SwiiZe** [comment]
Hi @nurzhaussyn , 
“r2-testapp-kotlin” is not meant to be built this way.
Did you try building the app through "r2-workspace-kotlin" ?
Please refer to the following link : [r2-workspace-kotlin](https://github.com/readium/r2-workspace-kotlin) and follow guidelines for branch "dev/testapp"

Irteza

**Comment by aferditamuriqi** [comment]
@nurzhaussyn I commented on your other issue that you've opened, this is a problem with jetpack, that hasn't built the libraries, I will take a look and see how quickly this can be solved, you shouldn't have to add any r2 modules yourself, but the testapp should compile and run without these issues

**Comment by aferditamuriqi** [comment]
@nurzhaussyn this has been resolved, jitpack is now building without issues, you should refresh your project and gradle dependencies
