### ISSUE TITLE
Rendition: automatic hyphenation is still lost in limbo

### ISSUE THREAD

**Issue by JayPanoz** [readium/r2-testapp-kotlin#23]
For more context, see https://github.com/readium/readium-css/issues/31 

The core issue is pretty much out of our hands since automatic hyphenation is handled by web’s rendering engines (browser, web view) but we can at least take some decision, UI- and UX-wise. 

Currently, we are managing hyphenation automatically when the user sets `text-align` ([see hyphens submodule](https://github.com/readium/readium-css/blob/develop/css/src/modules/user-settings-submodules/ReadiumCSS-bodyHyphens_pref.css#L9-L29)). If `text-align` is `justify` then we enable automatic hyphenation; if `text-align` is `left|right`, then we disable hyphenation. 

We have an [hyphenation-specific user setting](https://github.com/readium/readium-css/blob/develop/docs/CSS12-user_prefs.md#hyphens), which isn’t implemented in any app at the time being – and my recommandation would be to not implement it since the Android app is also meant to run on ChromeOS, on which automatic hyphenation is not implemented at all.

There’s another issue as regards Android though.

The bug has been fixed by Chromium and we can confirm automatic hyphenation now works in stock Android Oreo (> 8.0.0) with the latest Chrome/WebView but we are completely clueless when it comes to skinned and earlier versions of Android. 

I’ve had no luck on a Huawei-skinned Android Marshmallow (6.0.1) for instance, and automatic hyphenation just won’t happen on this device. But I can’t tell if it works on a stock Marshmallow device (6.0), a skinned and/or stock Nougat device (7.0), etc. 

It would at least be useful to know which earlier version got automatic hyphenation fixed. Indeed, Oreo has a market share of 4.6% while Nougat is at 30.8% ([source](https://developer.android.com/about/dashboards/)) so having this working in Nougat would make quite a huge difference. And if we can document that (“hyphenation is supported starting Android x.x.x”), it will also help app developers make an educated decision by checking Android’s distribution in the future.

**Comment by JayPanoz** [comment]
Note that, UI- and UX-wise, Chrome supports `hyphens: none|manual` (when set to `manual`, soft hyphens – `&shy;` in the markup – will be used to hyphenate words). 

Which brings the question of a11y. cc @llemeurfr 

Currently, disabling automatic and manuel hyphenation is tied to `text-align: left|right` in ReadiumCSS, but we could have something like an advanced “Disable hyphenation” setting, although it won’t re-enable hyphenation when unchecked on platforms that don’t support automatic hyphenation.

I really don’t know what’s our best option there.

**Comment by appndigital** [comment]
Bonjour @JayPanoz aucun rapport avec votre ticket mais avez-vous réussi à compiler la dernière version du code source de l'app ?
Il semble que cela ne fonctionne plus ni sur master ni sur dev.

Un ticket a été ouvert mais l'équipe Readium n'a pas répondu.

Merci d'avance de votre aide.

**Comment by appndigital** [comment]
@llemeurfr toutes mes excuses

**Comment by llemeurfr** [comment]
Je vais nettoyer cette issue de commentaires externes (en français) mais avant, merci de nous contacter via contact@edrlab.org pour nous donner qq infos sur ce que vous allez faire de notre SDK android : le pb avec l'open source, c'est que l'on sait rarement qui bénéficie de nos efforts.

**Comment by HadrienGardeur** [comment]
@JayPanoz is this issue still relevant in 2020?

**Comment by JayPanoz** [comment]
Yeah, the issue persists in Chromium’s issue tracker for ChromeOS. 

(As a sidenote, even with Edge moving to Chromium, it seems that MS didn’t make their the built-in dictionaries public).

**Comment by mickael-menu** [comment]
@JayPanoz Looks like the Chromium issue was closed in October, do you think there's still something to be done in Readium?

**Comment by JayPanoz** [comment]
As far as I can tell, it should be deployed in M88 so all we can do is wait for the next release of Chrome and test if it works – and report bugs if we find some. This issue can be closed as there’s nothing more we can do.

**Comment by mickael-menu** [comment]
Great, thanks!
