### ISSUE TITLE
No Server Port & serever.rootDir in Catalog.Activity.kt file

### ISSUE THREAD

**Issue by bleedweedsuz** [readium/r2-testapp-kotlin#24]
snipcode **CatalogActivity.kt**
```
private val server = Server()
private lateinit var books:ArrayList<Book>
private lateinit var booksAdapter: BooksAdapter
private lateinit var permissionHelper: PermissionHelper
private lateinit var permissions: Permissions

private val R2TEST_DIRECTORY_PATH = server.rootDir
```

how to remove this error i m new to this readium lib, i use  java i don't use kotlin so can u fix this error.
OR 
i m missing somethig

currenty using android studio 3.1.2 [latest]
error screen shot
![1](https://user-images.githubusercontent.com/10117919/40879931-f8b09b2a-66c7-11e8-853f-99757bc0fc1b.PNG)

**Comment by appndigital** [comment]
I confirm that the test app is not compiling anymore (master or develop).

Thanks

**Comment by aferditamuriqi** [comment]
This has been handled in the latest develop and master branches and should not be an issue anymore

**Comment by bleedweedsuz** [comment]
thanks for the reply i will look at it.
