### ISSUE TITLE
EPUB, handle page splitting while swiping

### ISSUE THREAD

**Issue by Sought** [readium/r2-testapp-kotlin#245]
Context: Trying to swipe towards new pages may skip chapters if they are still in the process of being split.

- The app should not apply user inputs immediately but queue them until the page splitting task ended.

Sample: https://www.ebooksgratuits.com/newsendbook.php?id=3000&format=epub

**Comment by HadrienGardeur** [comment]
Could you indicate the following information please:

- Android version
- [Version of the webview](https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en)
- Device used for this test

Thanks!

**Comment by Sought** [comment]
Sorry for the late answer.

Android Version: 6.0, API 23
Webview: 77.0.3865.92
Device: Huawei BTV-W09
