### ISSUE TITLE
import of publications during app install stops if screen orientation changes

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-testapp-kotlin#246]
There is a new feature that allows publication imports at install time. Import can be paused if    two publications have the same identifier (I stumbled on this case). If we change screen orientation during such a pause, publication imports stop.

**Comment by Sought** [comment]
Disabling Android's rotation behaviour (view destruction and re-creation) fixes this. But maybe there is a couple of issues I still didn't think of.
