### ISSUE TITLE
LCP, error messages to be optimized

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-testapp-kotlin#262]
If a revoked license is imported, the message is too long for the screen of a smartphone. 
"This license has been revoked by its provider on yyyy-mm-dd. The license was registered by 2..."
->
"This license was revoked by its provider on yyyy-mm-dd. It was registered by X devices."

If a cancelled license is importer, the message could be more adequate.
"You have cancelled this license on yyyy-mm-dd. "
->
"This license was cancelled on yyyy-mm-dd."

Rationale: usually a license is cancelled if the user calls the provider support and says that he cannot read the ebook because he has not an LCP compliant device. Meaning that the provider cancels the license, for the good of the user.

**Comment by aferditamuriqi** [comment]
changing this in iOS as well.
