### ISSUE TITLE
EPUB - Taping quickly after having scrolled stops the automated 'sticky' scrolling.

### ISSUE THREAD

**Issue by Sought** [readium/r2-testapp-kotlin#277]
Start a scroll from right to left, lift the scrolling finger, then tap quickly. The scrolling will get confused and stop until a new scrolling happens.

Taping will not fix it, unless it happens on the sides.

It happened on a Huawei BTV-W09 running Android 6.0 .

**Comment by mickael-menu** [comment]
This is fixed in 2.0.0-beta.1
