### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Murugeshrockey-RN** [readium/r2-testapp-kotlin#279]
I want to add the functionality of reading Epub files in my Android application by using readium's library but I am not able to find any documentation regarding this and am stuck at figuring out how I can integrate readium SDK. Is there any documentation I am missing? If not, can anyone point me to, or list out some necessary steps to follow to get this integration done correctly?

**Comment by RomanSoviak** [comment]
@Murugeshrockey-RN Hi there! Check this link https://github.com/readium/architecture

**Comment by mickael-menu** [comment]
The link given by @RomanSoviak is a good start to understand the architecture of Readium, but you have also more information on this repository for the Android integration: https://github.com/readium/r2-workspace-kotlin as well as a setup example.

Feel free to ask more specific questions if you need.

**Comment by mickael-menu** [comment]
We're going to work on documenting the toolkit this year.
