### ISSUE TITLE
Page is Not Loading

### ISSUE THREAD

**Issue by Murugeshrockey-RN** [readium/r2-testapp-kotlin#280]
![Screenshot_1579116304](https://user-images.githubusercontent.com/56159166/72465020-6d1b1880-37fc-11ea-8a19-4eebfa473e05.png)
 Getting error. While Adding publications from my application

**Comment by Sought** [comment]
Hello,

This issue is probably the same as this one:
- https://github.com/readium/r2-testapp-kotlin/issues/220

**Comment by mickael-menu** [comment]
Closing since it is probably obsolete. Feel free to reopen with more details if you still face this issue.
