### ISSUE TITLE
highlight area bound has wrong position.

### ISSUE THREAD

**Issue by dotmonkey** [readium/r2-testapp-kotlin#308]
function isPaginated in highlight.js got wrong result.
call to function setScrollMode is needed when WebViewClientCompat.onPageFinished called.

**Comment by mickael-menu** [comment]
Hi, thank you for reporting this bug.

Could you give more details on how to reproduce it? A book with which you had this issue, and a screenshot of the problem? Thanks

**Comment by dotmonkey** [comment]
the steps to reproduce the bug:
1. open book 'The Red Badge of Courage'.
2. go to chapter 1, page **2**(don't test on first page!).
3. select some text and create a highlight. the highlight is not shown.
4. turn on scroll mode and then turn it off, the highlight is shown.

**Comment by mickael-menu** [comment]
This bug seems to be fixed using the new Decorator API https://github.com/readium/r2-navigator-kotlin/pull/214
