### ISSUE TITLE
highlight data not updated after items deleted in outline activity.

### ISSUE THREAD

**Issue by dotmonkey** [readium/r2-testapp-kotlin#309]
steps to reproduce:
1. open any book in EPUB format.
2. select some text and create a highlight.
3. open outline activity and delete the highlight in the list.
4. go back to the reader activity, the highlight is not removed.

**Comment by mickael-menu** [comment]
This bug was fixed using the new Decorator API https://github.com/readium/r2-navigator-kotlin/pull/214
