### ISSUE TITLE
Highlights / Decorations

### ISSUE THREAD

**Issue by mickael-menu** [readium/r2-testapp-kotlin#311]
Issues related to highlighting content or any other kind of decorations attached to a rendition.

**Comment by mrifni** [comment]
I have two issues with the attached sample video file.

01. Highlights and notes are not working properly as their position isn't correct.
02. Audio attributes arent playing instead a blank space is showen and when click on the blank page it takes to some different pages.

[sample.zip](https://github.com/readium/r2-testapp-kotlin/files/5986919/sample.zip)
