### ISSUE TITLE
Not able to build the app

### ISSUE THREAD

**Issue by skumarudel** [readium/r2-testapp-kotlin#319]
Hi, Could you explain how can i fix this issue:
I am using Andriod studio 3.6.3, there are errors due to audio book activity...
I am tryinh: r2-testapp
Below is the error

-------------------------------------------------------------------------------------------
e: /Users/khushbooverma/Downloads/r2-testapp-kotlin-develop/r2-testapp/src/main/java/org/readium/r2/testapp/audiobook/AudiobookActivity.kt: (19, 30): Unresolved reference: extensions
e: /Users/khushbooverma/Downloads/r2-testapp-kotlin-develop/r2-testapp/src/main/java/org/readium/r2/testapp/audiobook/AudiobookActivity.kt: (20, 30): Unresolved reference: publication
e: /Users/khushbooverma/Downloads/r2-testapp-kotlin-develop/r2-testapp/src/main/java/org/readium/r2/testapp/audiobook/AudiobookActivity.kt: (31, 1): Class 'AudiobookActivity' is not abstract and does not implement abstract member public abstract fun locationDidChange(navigator: Navigator? = ..., locator: Locator): Unit defined in org.readium.r2.navigator.NavigatorDelegate
e: /Users/khushbooverma/Downloads/r2-testapp-kotlin-develop/r2-testapp/src/main/java/org/readium/r2/testapp/audiobook/AudiobookActivity.kt: (33, 5): 'locationDidChange' overrides nothing
e: /Users/khushbooverma/Downloads/r2-testapp-kotlin-develop/r2-testapp/src/main/java/org/readium/r2/testapp/audiobook/AudiobookActivity.kt: (33, 68): Unresolved reference: Locator
e: /Users/khushbooverma/Downloads/r2-testapp-kotlin-develop/r2-testapp/src/main/java/org/readium/r2/testapp/audiobook/AudiobookActivity.kt: (77, 16): Unresolved reference: it
e: /Users/khushbooverma/Downloads/r2-testapp-kotlin-develop/r2-testapp/src/main/java/org/readium/r2/testapp/audiobook/AudiobookActivity.kt: (103, 21): Unresolved reference: putPublicationFrom
e: /Users/khushbooverma/Downloads/r2-testapp-kotlin-develop/r2-testapp/src/main/java/org/readium/r2/testapp/audiobook/AudiobookActivity.kt: (118, 45): Unresolved reference: type
e: /Users/khushbooverma/Downloads/r2-testapp-kotlin-develop/r2-testapp/src/main/java/org/readium/r2/testapp/audiobook/AudiobookActivity.kt: (125, 25): Type mismatch: inferred type is String? but String was expected
e: /Users/khushbooverma/Downloads/r2-testapp-kotlin-develop/r2-testapp/src/main/java/org/readium/r2/testapp/audiobook/AudiobookActivity.kt: (128, 25): Unresolved reference: Locator
e: /Users/khushbooverma/Downloads/r2-testapp-kotlin-develop/r2-testapp/src/main/java/org/readium/r2/testapp/audiobook/AudiobookActivity.kt: (129, 25): Unresolved reference: Locator

**Comment by mickael-menu** [comment]
Hi,

Setting up the project is a bit complicated at the moment. If you want to test the `develop` branch, then all R2 dependencies must use the `develop` branch as well. You can use `r2-workspace-kotlin` for a quick setup.

Try running this:

`git clone --recurse-submodules -b dev/testapp https://github.com/readium/r2-workspace-kotlin.git r2-workspace-kotlin && cd r2-workspace-kotlin && git submodule foreach --recursive git checkout develop`

**Comment by mickael-menu** [comment]
Feel free to reopen this issue if you still face it.
