### ISSUE TITLE
Playing epub with smill (MP3)?

### ISSUE THREAD

**Issue by LeoDiasDev** [readium/r2-testapp-kotlin#32]
Hello,

In this library can I set up for epub reading with audio? If yes, how to do it?

Hugs,
Leonardo

**Comment by llemeurfr** [comment]
This is a feature that will have be developed in the future. It will be an epic, named "Media-overlays" (this is the term used in EPUB).

Would you help the Readium community build this feature?

**Comment by llemeurfr** [comment]
See #52, which is currently in the ZenHub Ice Box, waiting for help.
