### ISSUE TITLE
Slow performance when using cyrrylic font 

### ISSUE THREAD

**Issue by RomanSoviak** [readium/r2-testapp-kotlin#334]
Hi there! I observe that working with the book, which contains Cyrillic font takes too long. Performance is good when I open English book, but a little slow with Cyrillic font. My test books are here https://drive.google.com/drive/folders/1_cS5TyA4epxtyLoV73OvaHv3NK7QPnKz?usp=sharing

**Comment by RomanSoviak** [comment]
Try to change font size during working with book

**Comment by mickael-menu** [comment]
I'm closing this issue as it seems to be a duplicate of this other one: https://github.com/readium/r2-navigator-kotlin/issues/145
