### ISSUE TITLE
Convert "LocationChange" and Highlight to CFI Format

### ISSUE THREAD

**Issue by manolisep** [readium/r2-testapp-kotlin#336]
Hi, has any way to covert the Location to a CFI format and vice versa?

Example: epubcfi(/6/2[Section0001.xhtml]!/4/4/2/1:0)

Thanks!!

**Comment by mickael-menu** [comment]
Hi @manolisep,

There's no way to convert a `Locator` to CFI, as they contain two very different way to locate a position. Unfortunately, we don't have any plan to support CFI anytime soon.
