### ISSUE TITLE
App Removed From PlayStore

### ISSUE THREAD

**Issue by nidhinprathap** [readium/r2-testapp-kotlin#340]
Hi,
Has the demo app been removed from play store? Whenever I try to access the url it says 
**We're sorry, the requested URL was not found on this server.**
 Url :-

[PlayStore Link](https://play.google.com/store/apps/details?id=org.readium.r2reader)

---

Edit from moderator: [Jump to official answer](https://github.com/readium/r2-testapp-kotlin/issues/340#issuecomment-674720421)

**Comment by mickael-menu** [comment]
@nidhinprathap Yes we decided to remove R2 Reader from the stores:

> We've taken an impacting decision during the last Readium call: remove R2 Reader from "production" in the Google and Apple App Stores, keep it as a private app for tests and demos. The question is now: how do we manage developer's requests to access R2 Reader, e.g. from people willing to test their LCP server using R2 Reader without having to compile it?
> https://readium.slack.com/archives/C0AN4MN1J/p1594369887292700

Please get in touch with @llemeurfr if you need an access.

**Comment by nidhinprathap** [comment]
Oh thanks for the update. Any specific reason for taking this step?

**Comment by mickael-menu** [comment]
End users assumed that it was a regular reader apps and expected support and polished features. The purpose of R2 Reader was to showcase the capabilities of Readium 2, but now there are plenty of apps on the market using Readium 2.

**Comment by nidhinprathap** [comment]
Ok thanks

**Comment by stevenzeck** [comment]
@mickael-menu are you able to upload an APK when you do a GitHub release?  That would be a decent workaround, although people would need to allow unverified APKs.

**Comment by mickael-menu** [comment]
@stevenzeck Yesterday during the dev call we decided to continue pushing the builds on the beta channel ( https://play.google.com/apps/testing/org.readium.r2reader ). Would that answer your needs?

**Comment by Josh68** [comment]
Any way to get this beta if you don't already have it? I got Thorium installed on Linux and quite like it. Thanks

**Comment by mickael-menu** [comment]
@Josh68 You should be able to join the beta and download the app from https://play.google.com/apps/testing/org.readium.r2reader

However, the scope is quite different from Thorium. R2 Reader is really a test app and you might experience data loss between two versions. So I wouldn't use it as your daily reading app.

**Comment by Josh68** [comment]
Thanks. The public version link
<https://play.google.com/store/apps/details?id=org.readium.r2reader&ah=gp-XFDbnm56idYNSyW9PlvvKoj4>
on the testing page goes nowhere. This is why I asked.

**Comment by mickael-menu** [comment]
You need to open it from an Android device.

**Comment by Josh68** [comment]
I have, no luck. 🤔

**Comment by llemeurfr** [comment]
As a summary: the test app named **R2 Reader Android** was developed for helping developers check the interest of the **Readium Mobile Android** toolkit before they start playing with it. Readium developers initially put a version of this app on the PlayStore for easy access. But some users complained about the lack of user support for this app, the fact that their ebooks could be lost after an update etc. 

Readium developers therefore decided to keep the app on the beta channel only, with a public link enabling anybody to become tester: https://play.google.com/apps/testing/org.readium.r2reader    

R2 Reader will stay a beta channel  test app forever. Users willing to download a good reading application based on Readium Mobile should look at [Awesome Readium](https://github.com/readium/awesome-readium), where they will find a list of such apps localized in different languages, with different feature sets. Some of these apps are generic and can import EPUB files from any source like R2 Reader, others are tied to a specific provider. PRs are welcome when apps are missing or to provide additional info on the apps.

**Comment by Josh68** [comment]
@llemeurfr, thanks for re recap. The thing I was trying to make clear is that the testing page link works fine, but the link to install the "public" version of the app in the Play Store doesn't work, for me at least, including on an Android device (in my case, a Motorola X4 running Pie). 

The page link you reference tells me I am a tester, but I did not have the app installed prior to the changes the development team made. I don't know if this is useful information, but I thought I'd let you know. Again, I don't want to take up dev's time with the issue. 

I've also tried some of the apps on Awesome Readium, and so far haven't found one that doesn't seem to be tied to specific sources, but I'll revisit that option. I keep looking for a favorite e-reader on Android.

**Comment by nidhinprathap** [comment]
@llemeurfr become a Beta Tester link is available but once u accept and then go to download page it shows app not available.

**Comment by mickael-menu** [comment]
It looks like the beta is only available to people that already downloaded the app when it was in production. But since we removed it from the PlayStore, we're stuck for newcomers...

So from now on, we'll also release an APK for each new version. You can find the 2.2.0 one from the releases page: https://github.com/readium/r2-testapp-kotlin/releases/tag/V2.2.0
