### ISSUE TITLE
Opening extracted epub files

### ISSUE THREAD

**Issue by rahulk11** [readium/r2-testapp-kotlin#341]
Hi, is there any option to open an extracted epub? I have epubs which are not zipped but are extracted into their own directories.
For example contents of an epub "test.epub" is extracted into directory "test".

**Comment by mickael-menu** [comment]
Yes it should be supported on the `master` branch:

https://github.com/readium/r2-streamer-kotlin/blob/986117e6ca4286a5aca477dacb20e373042e379d/r2-streamer/src/main/java/org/readium/r2/streamer/parser/epub/EpubParser.kt#L101-L108

Have you tried giving directly a path to a directory to the `EpubParser`?

Also in the upcoming 2.0.0 alpha, we've refactored this part and exploded directories will be supported by all archive-based parsers in a more systematic way.

**Comment by rahulk11** [comment]
I figured it out by debugging. Thanks for the response anyway.
