### ISSUE TITLE
The content Moves up and down when used on a Notch Device

### ISSUE THREAD

**Issue by nidhinprathap** [readium/r2-testapp-kotlin#342]
When using highlights or notes on a notch device the marker position jumps up and down based on the visibilty of Action Bar.
Please see the attached images. 
This is with Notch and full screen
![image](https://user-images.githubusercontent.com/21108668/88628969-4e131280-d0cc-11ea-8191-d3981ca1203d.png)

This is when The Action bar is shown
![image](https://user-images.githubusercontent.com/21108668/88629029-64b96980-d0cc-11ea-9d5d-277113c854ee.png)

The highlighted marker keeps jumping.. even the webview moves up and down based on action bar visibility

**Comment by mickael-menu** [comment]
@nidhinprathap This issue should be fixed in the latest version (2.0.0-beta.1). Feel free to reopen if you still face it.
