### ISSUE TITLE
Hyperlinks/Glossary not redirecting to proper page

### ISSUE THREAD

**Issue by nidhinprathap** [readium/r2-testapp-kotlin#351]
While debugging the code saw that there is a javascript call to function "**scrollAnchor**" in **R2EpubPageFragment** 

```
if (url!!.indexOf("#") > 0) {
    val id = url.substring(url.indexOf('#'))
    webView.loadUrl("javascript:scrollAnchor('$id');")
    locations = Locations(fragment = id)
}
```
But i can't see the definition of the above-mentioned function. Are we missing something here ?

**Comment by mickael-menu** [comment]
@nidhinprathap This piece of code was removed in the latest version (2.0.0-beta.1) and jumping to an anchor from the table of contents works fine for me. Would you mind checking it out again and reopening the issue with a sample book if you still have the problem? Thanks
