### ISSUE TITLE
highlight and navigation problem for arabic files

### ISSUE THREAD

**Issue by marouenak** [readium/r2-testapp-kotlin#360]
Hello,
While testing on an arabic epub i noticed two problems: 

1. highlighting is not rendered correctly.
For example, for the file attached here:
- Go to the third chapter 
- Highlight a word. 
=>Nothing happens

2. Navigation in file is not correct
- When choosing a chapter from the menu => navigation goes another chapter
- Although the language in metadata is arabic, Navigation seems to be LTR between chapters

[Jorge Zaydan_arabic language essay.zip](https://github.com/readium/r2-testapp-kotlin/files/5333987/Jorge.Zaydan_arabic.language.essay.zip)

Hope this will be useful to you,
Marouen Ahmed Kadri

**Comment by marouenak** [comment]
It appears that the migration resolved some of the issues here. Even though i am at trouble for the sens of  navigation between chapters in rtl context. I close it then for now

**Comment by mickael-menu** [comment]
Hi Marouen,

Thanks, new test files are always useful. In which version/branch of the Readium toolkit do you have the issue?

**Comment by marouenak** [comment]
Hi Mickael,
I have tested first on V2.0.0
Then, I have tested these yesterday on dev/testapp branch last modifs.
hope this will help

**Comment by mahdisadeghi74** [comment]
I have this problem but differences is that when use Persian language in pagination mode(not scroll mode)
hope this will help

**Comment by mahdisadeghi74** [comment]
> Hi Marouen,
> 
> Thanks, new test files are always useful. In which version/branch of the Readium toolkit do you have the issue?

I have this problem but differences is that when use Persian language in pagination mode(not scroll mode)
hope this will help

**Comment by mahdisadeghi74** [comment]
When call **createHighlight()** inside **R2BasicWebView.kt**: `locator.locations.prograssion `is equal  `="progression":4.6264169780352646E-4}` always

This when happen than **`scrollmode == false`** and **webview has 1 page in its fragment**

and in this situation highlights not work in RTL languages

If you can please fix it. thank you.

**Comment by mahdisadeghi74** [comment]
I fixed it:)
In `function createHighlightDom(win, highlight, annotationFlag)` inside **highlight.js**:
I change below line like **/iPhone|iPad|iPod/i** devices:
        `xOffset = paginated ? (-scrollElement.scrollLeft) : (-scrollElement.scrollLeft) ;`

It is necessary change TouchEvent functions like this.

with this code problem solved on **rtl** and **ltr** mode.

**Comment by mickael-menu** [comment]
@mahdisadeghi74 Thanks, would you mind creating a PR to push your fix to Readium?

**Comment by mickael-menu** [comment]
RTL pagination should be fixed in `2.0.0-beta.1`, but I'm keeping this opened since the highlight issue should still be there.

**Comment by mickael-menu** [comment]
Seems to be fixed with the new Decorator API https://github.com/readium/r2-navigator-kotlin/pull/214

<img src="https://user-images.githubusercontent.com/58686775/127895698-72985d85-d7df-43eb-bf5c-2f0cb6c27c3f.png" width="400px"/>
