### ISSUE TITLE
Can not generate signed build 

### ISSUE THREAD

**Issue by mahdisadeghi74** [readium/r2-testapp-kotlin#374]
I use r-shared, r-streamer and r-navigation repository in my application but when I try generate signed build receive below error:
`Type org.readium.r2.shared.publication.Locator$Locations$Companion is defined multiple times:`

I don't know why?

**Comment by mickael-menu** [comment]
Are you able to see all the places where `Locations:$Companion` is defined in the build error? It should only be defined in `r2-shared-kotlin`, in `Locator.kt`.

Also which version of Readium are you using?

**Comment by mickael-menu** [comment]
Feel free to reopen with more details if you still have the issue.
