### ISSUE TITLE
Highlight display position error

### ISSUE THREAD

**Issue by 312654929** [readium/r2-testapp-kotlin#376]
Some Chinese epubs (not all of them, after testing, this situation does not happen in all Chinese epubs), click highlight, but the display position is not correct, generally it will deviate about 1-2 lines below the punctuation

**Comment by 312654929** [comment]
After testing, I found that if the default is horizontal page flipping mode, after turning to scroll mode, the highlight problem will be solved. After that, no matter in horizontal page flipping or scroll mode, there will be no problem. The premise is to open the scroll mode。

**Comment by 312654929** [comment]
![image](https://user-images.githubusercontent.com/50512913/103283587-f3cc0400-4a13-11eb-850e-123c4db7248e.png)

The reason is that when the function is opened for the first time, it returns false. Only when the scroll mode option is called will it be judged again. That is, when opening e-books, there is no CLASS_PAGINATED class by default

**Comment by mickael-menu** [comment]
Hi @312654929, thanks for reporting this issue.

Could you send a screenshot or a video showing the problem, so I understand better the issue?

Also if you can share a Chinese EPUB exhibiting the problem, that would be very useful.

**Comment by 312654929** [comment]
Hello，how's it going? I have sent it to your email

**Comment by mickael-menu** [comment]
@312654929 Yes I received it, but I don't have the time to take a look at this issue at the moment. You can try debugging it yourself and submit a pull request if you want.

(Note to self: mail subject "Highlight display position error")

**Comment by mickael-menu** [comment]
There's a new API to draw highlights in Readium's `develop` branches, see this PR https://github.com/readium/r2-navigator-kotlin/pull/214

There won't be any more fixes in the legacy highlights implementation (unless external contributions), so please check if you still have the same problem with this new API, in which case we'll reopen this issue. You can test it out in the latest Test App.
