### ISSUE TITLE
Locator observer isnt firing

### ISSUE THREAD

**Issue by mrifni** [readium/r2-testapp-kotlin#393]
I have this code below in EpubActivity (copied from test app)
```
currentLocator.asLiveData().observe(this@EpubActivity, Observer { locator ->
                locator ?: return@Observer

                Timber.d("locationDidChange position ${locator.locations.position ?: 0}/${positionCount} $locator")
                booksDB.books.saveProgression(locator, bookId)

                if (::screenReader.isInitialized && locator.locations.progression == 0.0) {
                    screenReader.currentUtterance = 0
                }
            })
```

And I start the EpubActivity using below code

```
val intent = NavigatorContract().createIntent(context, NavigatorContract.Input(
                                    file = customFile,
                                    format = format,
                                    publication = publication,
                                    bookId = bookId.toLong(),
                                    initialLocator = booksDB.books.currentLocator(bookId.toLong()),
//                                    deleteOnResult = remoteUrl != null,
                                    baseUrl = Publication.localBaseUrlOf(file.name, localPort)
                            ))

                            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                            context.startActivity(intent)
```

So the problem is locater doesnt seems to work whenever I made a reading progress with the page and I cant see `locationDidChange position` is printed.
What am I missing ? test app seems to work though if i run it seperately

**Comment by mickael-menu** [comment]
Looks good. Where did you put the observer code exactly?

Also, maybe you didn't set up Timber in `Application.onCreate()`. Try using directly `Log.d()`.

```kotlin
Timber.plant(Timber.DebugTree())
```

**Comment by mrifni** [comment]
`Where did you put the observer code exactly?` I have copied the whole EpubActivity.kt from the testapp itself. And made no changes.

`Also, maybe you didn't set up Timber in Application.onCreate(). Try using directly Log.d().` I have added standard logs like `println`, logs worked on other classes so hopefully it will should work in EpubActivity.kt as well.

**Comment by mickael-menu** [comment]
Not sure what might be the issue then...

I'm closing the issue since it doesn't seem to be a bug in the toolkit. But please do follow-up if you find something, and I might reopen it.
