### ISSUE TITLE
Hi brother I can not find 'MaterialRenewListener'  version="2.0.0-beta.1"

### ISSUE THREAD

**Issue by wukuiqing49** [readium/r2-testapp-kotlin#395]
![image](https://user-images.githubusercontent.com/13608463/109266402-fe9feb00-7842-11eb-83e8-6344ec104013.png)

**Comment by mickael-menu** [comment]
`MaterialRenewListener` is not yet released, it's in the `develop` branch. However I will do a new `2.0.0-beta.2` release today which will contain it.

**Comment by wukuiqing49** [comment]
Nice job

**Comment by wukuiqing49** [comment]
> `MaterialRenewListener` is not yet released, it's in the `develop` branch. However I will do a new `2.0.0-beta.2` release today which will contain it.

Nice job, thanks.
