### ISSUE TITLE
Error empty response

### ISSUE THREAD

**Issue by RomanSoviak** [readium/r2-testapp-kotlin#401]
![image](https://user-images.githubusercontent.com/26696190/111967334-97531f00-8b00-11eb-9796-13334e3435bb.png)

While opening debug .epub file with test app. After restarting it works

**Comment by mickael-menu** [comment]
Could you share the problematic EPUB and more detailed steps to reproduce the issue?

**Comment by RomanSoviak** [comment]
Epub is okay. It works well on different devices. @mickael-menu it's doesn't matter which .epub I use.

**Comment by mickael-menu** [comment]
Unfortunately this issue is not actionable. Please reopen an issue with enough details to be able to reproduce the problem.
