### ISSUE TITLE
Replace kovenant with coroutines

### ISSUE THREAD

**Issue by stevenzeck** [readium/r2-testapp-kotlin#404]
This would be applicable for the [shared](https://github.com/readium/r2-shared-kotlin), [opds](https://github.com/readium/r2-opds-kotlin) and testapp modules.

Kovenant has not been updated in almost 5 years and Fuel supports [coroutines](https://github.com/kittinunf/fuel/tree/master/fuel-coroutines).  Consider using them instead and remove the dependency on kovenant.

**Comment by mickael-menu** [comment]
Yes, definitely agree. I also want to remove any third-party dependency from the project for the HTTP requests. `HttpURLConnection` is enough for our use cases, I implemented a `DefaultHttpClient` with it here: https://github.com/readium/r2-shared-kotlin/pull/148 Reading apps can always implement their own `HttpClient` with Fuel, OkHttp or whatnot.

**Comment by stevenzeck** [comment]
Great. Can that safely replace the Fuel code being used by the opds parsers without breaking backwards compatibility? Would have to support promises for that.

The opds module can otherwise be updated to deprecate those existing functions that return promises, and add new ones that use that http code and no kovenant code at the same time.

**Comment by mickael-menu** [comment]
No there will be a transition period with an alternative coroutine API in `r2-opds-kotlin` before deprecating Fuel in 3.0.
