### ISSUE TITLE
Android 12 (S) support

### ISSUE THREAD

**Issue by stevenzeck** [readium/r2-testapp-kotlin#410]
Android 12 has been in developer preview since late February, with the final release probably in September or October.  Need to make sure libraries are all compatible and the testapp works.  A summary of changes is here:  https://developer.android.com/about/versions/12/summary and apps that target Android 12:  https://developer.android.com/about/versions/12/behavior-changes-12.

So far I've only noticed that the testapp's manifest needs to be updated to explicitly declare the `android:exported` attribute for activities, services and broadcast receivers. `R2DispatcherActivity` and `MainActivity` (once #403 is merged) both need exported to be set to true, while the others can be false.

**Comment by mickael-menu** [comment]
Thanks for testing this out 👍
