### ISSUE TITLE
locator json format issue

### ISSUE THREAD

**Issue by mrifni** [readium/r2-testapp-kotlin#428]
```
{"href":"\/titlepage.xhtml","type":"application\/xhtml+xml","locations":{"progression":0,"position":1,"totalProgression":0}}
```

this is what I get in the test app but it doest look like a valid json for some reason. Json parser libraries i use gives me this value instead, note the `\` is gone

```
{"href":"/titlepage.xhtml","type":"application/xhtml+xml","locations":{"progression":0,"position":1,"totalProgression":0}}
```

and the above json when sent doesnt work with the locator also i think.

**Comment by mickael-menu** [comment]
How did you get this JSON string?

**Comment by mrifni** [comment]
fun saveProgression(locator: String) = viewModelScope.launch {
                 println(locator)
}

this code is in `ReaderViewModel.kt` line no 50 i think

**Comment by mickael-menu** [comment]
This JSON string is generated by the standard `JSONObject`, not in Readium. Here `toJSON()` returns a `JSONObject`:

https://github.com/readium/r2-testapp-kotlin/blob/763052112fbfe91aaaa16c1400e5cc5d75d88bf7/r2-testapp/src/main/java/org/readium/r2/testapp/reader/BaseReaderFragment.kt#L45

Here's why: https://stackoverflow.com/questions/1580647/json-why-are-forward-slashes-escaped

If you don't want to have them escapes, [you will need to find a workaround](https://stackoverflow.com/questions/16563579/jsonobject-tostring-how-not-to-escape-slashes).
