### ISSUE TITLE
Spacing doesn't work first time

### ISSUE THREAD

**Issue by ajay9889** [readium/r2-testapp-kotlin#430]
### When reading the book and click the option "Aa" and selecting the spacing option the first time nothing happenes. 

**When clicking back and restarting the App and opening again it works**

**Comment by mickael-menu** [comment]
Please reopen a new issue following the Bug Report issue template https://github.com/readium/r2-testapp-kotlin/issues/new?assignees=&labels=&template=bug_report.md&title=
