### ISSUE TITLE
Spacing is not working

### ISSUE THREAD

**Issue by ajay9889** [readium/r2-testapp-kotlin#431]
### step to reproduce this issue on Android version 2.0.0 latest version
1. Fresh install the App.
2. Click on any ePub book to Read
2. Select the Font setting (Aa) option from the action bar
3. In Spacing option first time (Justify, left align or right align)
4. It doesn't change and reflect in the view.
5. It works when we force close the and restart again.

### Expected behavior

It should work as aspected based on the user selections. This is happening in the readium test app as well

**Comment by mickael-menu** [comment]
[Please next time follow the bug report issue template](https://github.com/readium/r2-testapp-kotlin/issues/new?assignees=&labels=&template=bug_report.md&title=), as it helps make sure we have all the infos necessary to reproduce an issue.

**Comment by stevenzeck** [comment]
Yeah for whatever reason the property `setProperty("--RS__advancedSettings", "readium-advanced-on");` needs to be set in the root style before that starts to work.  Not sure the best place to fix it to be honest.

**Comment by mickael-menu** [comment]
Changing the text alignment requires to have the publisher's defaults to OFF (`readium-advanced-on`).

So the correct behavior should be to automatically switch off the publisher's defaults when changing any "advanced" setting, and apply the CSS together.

**Comment by ajay9889** [comment]
It is fixed. thanks
