### ISSUE TITLE
Top bar (header) doesnt show sometimes

### ISSUE THREAD

**Issue by mrifni** [readium/r2-testapp-kotlin#436]
On latest develop branch i noticed most of the time top bar doesnt show when tap on the reader screen. It shows first time but after reading few pages ( swiping left-right quickly ) the top doesnt appear when touch on the screen.

**Comment by qnga** [comment]
Which kind of publication did you use?

**Comment by mickael-menu** [comment]
Please follow the [bug report issue template](https://github.com/readium/r2-testapp-kotlin/issues/new?assignees=&labels=&template=bug_report.md&title=) when reporting new issues, as it helps us reproduce the problem.

**Comment by mrifni** [comment]
added another issue with the template https://github.com/readium/r2-testapp-kotlin/issues/437
