### ISSUE TITLE
Audio tags are greyed out or disabled on live phone

### ISSUE THREAD

**Issue by mrifni** [readium/r2-testapp-kotlin#443]
### What happened?

Some of epubs I use have audio tags and they used to work but suddenly stopped working. When I debug the application audios always work on the emulator but doesnt work on the live mobile device ( OnePlus 5 ), when I debug on chrome browser for some reason it shows `cancelled` in the network tab. ( please see the attached screenshots )

### How to reproduce?

Open the sample book attached and go to the `About von Harbou` page.

### Environment

latest develop branch

#### Testing device

* Android version: Android 10
* Model: Oneplus 5
* Is it an emulator? No

<img width="1162" alt="Screenshot 2021-07-14 at 13 51 38" src="https://user-images.githubusercontent.com/1643992/125625955-0f1130ee-9bac-4852-9dea-ca84d1894f47.png">
<img width="1203" alt="Screenshot 2021-07-14 at 13 52 14" src="https://user-images.githubusercontent.com/1643992/125625964-e6af857d-bd55-4f54-868c-ac4ad6ada012.png">

[6.epub.zip](https://github.com/readium/r2-testapp-kotlin/files/6816187/6.epub.zip)

**Comment by mrifni** [comment]
any idea ?

**Comment by mickael-menu** [comment]
It might be because the referenced URLs are remote. I'm not sure why the web view is cancelling the requests though.

**Comment by mrifni** [comment]
Ive tested it, its happening because of remote host blocking the requests coming from the reader. When I change the audio links its started working.

May be we can close this issue ?

**Comment by mickael-menu** [comment]
Yes, it might be because the user agent doesn't match a regular browser. Thanks for investigating.
