### ISSUE TITLE
Cannot open .lcpl license file

### ISSUE THREAD

**Issue by tmanev** [readium/r2-testapp-kotlin#444]
### What happened?
Installed r2-testapp-2.2.0.apk.
I tried to open the license file, and it complains with the error:
`fulfillment error: liblcp is missing on the classpath`

### Expected behavior

To be able to open the lcp book.

### How to reproduce?

1. Install r2-testapp-2.2.0.apk
2. Open .lcpl file

#### Readium versions

* `r2-testapp-2.2.0.apk`:

#### Testing device

* Android version: 11
* Model: Samsung Note 10+
![Screenshot_20210716-141424_R2_Reader 1](https://user-images.githubusercontent.com/7486238/125946496-2b08a0c8-00f7-46f8-b307-dca4efca72ec.jpg)

**Comment by mickael-menu** [comment]
Looks like I forgot to enable LCP while building the APK. Are you able to build from the sources or you really need the APK?

**Comment by tmanev** [comment]
I'm not able to build the APK. I do not have the environment to build it.
I really need the APK for testing/checking the LCP.

**Comment by mickael-menu** [comment]
@tmanev I built it again, you can download it from https://github.com/readium/r2-testapp-kotlin/releases/tag/2.2.0
You can close this issue if it works for you.

**Comment by tmanev** [comment]
Seems to work now. Thanks for the re-build.
