### ISSUE TITLE
Increase content of before and after of Locator

### ISSUE THREAD

**Issue by amkrys** [readium/r2-testapp-kotlin#447]
Hello devs, 
We have a Locator class to highlight word and it also have after and before variables which gives few lines after or before highlighted word .

 I want to increase the content shown by this Locator.
 Is it possible ? if yes, how?
 Please Help 
Thank you
![Screenshot_2](https://user-images.githubusercontent.com/70586998/127479044-3fe8c697-f9a3-4ba7-90bd-d4361e779d4f.png)

**Comment by mickael-menu** [comment]
How are you getting these locators? In the latest release, the Readium toolkit is actually not using `before` and `after`.

**Comment by amkrys** [comment]
I am using a library which is internally using r2-redium 
Link to library is -
https://github.com/FolioReader/FolioReader-Android

**Comment by mickael-menu** [comment]
Okay then you should open an issue on their repo, because `before`/`after` are most likely computed by FolioReader.

**Comment by amkrys** [comment]
> Okay then you should open an issue on their repo, because `before`/`after` are most likely computed by FolioReader.

No its not related to FolioReader and i am sure about that, that's posted not there.

**Comment by mickael-menu** [comment]
We don't set `before` or `after` in Readium, so I don't know how to help you. Feel free to take a look at the codebase.

**Comment by amkrys** [comment]
See the package in the above screenshot
