### ISSUE TITLE
able to download the same book from catalog

### ISSUE THREAD

**Issue by gelojavonitalla** [readium/r2-testapp-kotlin#459]
## Bug Report

Not actually sure if this is a bug or an improvement.

### What happened?

![Screenshot_20210901-154100_R2 Reader](https://user-images.githubusercontent.com/276042/131679838-a91be907-4124-4340-aca5-cb6786e1b8ce.jpg)

When you go to catalog and download an already existing book in the bookshelf, a copy of that book is added in the bookshelf. 

### Expected behavior

If the book is already existing in the bookshelf, the button should be open/read instead of download.

### How to reproduce?

1. Go to Bookshelf and check the books available
2. Go to Catalogs/OPDS 2.0 Test Catalog
3. Download one of the existing books in the library (Step 1)
4. Go back to the Bookshelf. There are now two copies of the selected book

#### Readium versions

Running on latest develop branch

#### Development environment

Android Studio Arctic Fox

#### Testing device

* Android version: 10
* Model: Note 8
* Is it an emulator? No

### Additional context

I'm willing to fix/improve this feature

**Comment by mickael-menu** [comment]
I'm a bit on the fence for this one.

On the one hand, the Test App is not meant to be a full-fledged reading app. We want to keep the Test App simple to showcase how to use the Readium toolkit, so less code is better for understanding.

On the other hand, knowing how to correctly identify a "unique" publication is important for a real reading app.

I think I would prefer writing a best practice reference note in [`architecture`](https://github.com/readium/architecture) or [`mobile`](https://github.com/readium/mobile).

**Comment by llemeurfr** [comment]
Decision from the Readium core devs: the test app is ... a test app. The code must be as small as possible there. If we add heuristics to check duplicates, it will only work to a certain extent. Also the UI would become more complex (for a test app). 

And some apps allow duplicates (sometime different versions of the same book). 

Book identifiers are not 100% reliable. A hash of the publication is a solution used in some apps.
