### ISSUE TITLE
Table of contents jumps to previous chapter

### ISSUE THREAD

**Issue by YorickPieters** [readium/r2-testapp-kotlin#51]
Occurs on: Play Store version (seen on both beta 1 and beta 2)
App version: 1.0.1
Github tag: v1.0.0-beta.2

Open a sample book (Red badge of Courage)
Click on chapter 7
Chapter 6 is rendered

**Comment by clementbmn** [comment]
This has been fixed, you should have the corrected version next week

**Comment by aferditamuriqi** [comment]
has been addressed here, closing this issue as it is already merged into develop branch and tagged for beta.3 https://github.com/readium/r2-navigator-kotlin/issues/7
