### ISSUE TITLE
change the sponsor line and logo in the info panel 

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-testapp-kotlin#59]
The new line is "R2 Reader ... help of the French State." + the PNG logo of the French Republic.

**Comment by aferditamuriqi** [comment]
fixed with these commits 
https://github.com/readium/r2-testapp-kotlin/commit/53223afa9dfdea1e39cf15281dd0260f30d7f7a3
https://github.com/readium/r2-testapp-kotlin/commit/be7d4a7e0d5651634f927dba6adce48efc7df98f
