### ISSUE TITLE
Fresh build is apparently broken in master

### ISSUE THREAD

**Issue by rkwright** [readium/r2-testapp-kotlin#64]
Installed the latest Android Studio, 3.1.3 and then cloned the r2-kotlin-app repo (master). Opened it with AS, which caused AS to update all sorts of dependencies, but then after a lot of running, it issue these errors:

    org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies 
    for configuration ':r2-testapp:debugRuntimeClasspath'.

The complete output of the errors is here:

[AS_Build_Errors_20180718.txt](https://github.com/readium/r2-testapp-kotlin/files/2206902/AS_Build_Errors_20180718.txt)

**Comment by egidijusk** [comment]
@rkwright Did you manage to build the app? I have the same problem. What about dependencies mentioned in the README? To me they look like part of the app? If you succeeded to build the app, please let me know how. Thank you.

**Comment by aferditamuriqi** [comment]
with the latest changes in https://github.com/readium/r2-workspace-kotlin and also in each repository, this issue should not be current anymore. 

by changing the 
ext.r2branch = 'develop' to ext.r2branch = 'master' all r2 dependences will use the proper branch
example:
https://github.com/readium/r2-workspace-kotlin/blob/int/testapp/build.gradle#L6

I've tested all different workspaces and also the test app https://github.com/readium/r2-testapp-kotlin/blob/develop/build.gradle#L6

@rkwright, I am closing this issue, but if there is anything still not working feel free to reopen.
