### ISSUE TITLE
Epub Lcp : Bad gateaway leading to an infinite progression loop

### ISSUE THREAD

**Issue by IdMostapha** [readium/r2-testapp-kotlin#66]
I tried to open an epub with and lcp license, where the resources links are down.

During the execution, a error 502 : Bad Gateaway is catched but there's no return of it in the app, letting the progress bar running infinitely.

**Comment by llemeurfr** [comment]
As a precision, the license was generated by a test license server that has been put down. Therefore the status document cannot be fetched anymore. The book should still be readable.
