### ISSUE TITLE
LCP: missing register event on new licenses and publcation doesn't open

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-testapp-kotlin#91]
Steps to reproduce:
Get a new license, ready state, from the LCP server
Open the book -> the status document call is not followed by  register call
The book is open, it can be read
Close the book
Open the book -> the message "Please ait" appears briefly", then we stay in the library view.

**Comment by pavelric** [comment]
Importing the book twice in the catalog will trigger the register event the second time it is added
